env:
  browser: true
  node: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  {
    no-plusplus: 0,
    class-methods-use-this: 0,
    no-multi-assign: 0,
    import/prefer-default-export: 0,
    new-cap: 0,
  }
